---
# vars file for ec2

instance_tag:
      - control-demo
      - node1-demo
      - node2-demo

python_pkgs:
      - boto
      - boto3

sg_name: default
region_name: ap-northeast-3
# subnet_name: subnet-0a520f7a16813dbcb
# ami_id: ami-09a7535106fbd42d5 #ubuntu 22.04 LTS
ami_id: ami-0c1907b6d738188e5 #ubuntu 20.04 LTS

keypair: mynephio2025
instance_flavour: t3.xlarge

# vpc_id: vpc-0de3cf98b112bed75
vpc_name: nephio-5g
vpc_cidr_block: 192.168.0.0/20
subnet_cidr_block: 192.168.0.0/24
